######################################################################
# START OF PLUGINS
######################################################################

# Plugin manager for tmux 
set -g @plugin 'tmux-plugins/tpm'

# Simple tmux options for anyone
set -g @plugin 'tmux-plugins/tmux-sensible'

# Gruvbox theme for tmux - powerline support!
set -g @plugin 'egel/tmux-gruvbox'

# Persistent tmux envs across system restarts
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Continuous saving of tmux environment
set -g @plugin 'tmux-plugins/tmux-continuum'

#######################################################
# TMUX-CONTINUUM 
#######################################################

# Enables restoral of saved tmux config
set -g @continuum-restore 'on'

# How often to save a tmux layout
set -g @continuum-save-interval '10'

#######################################################
# TMUX-RESURRECT
#######################################################

# Capture contents of each pane 
set -g @resurrect-capture-pane-contents 'on'

# Set to resurrect neovim sessions 
set -g @resurrect-strategy-nvim 'session'

# Processes to resurrect 
set -g @resurrect-processes '~julia'

#######################################################
# TMUX-SENSIBLE
#######################################################

# Increase scrollback buffer size
set -g history-limit 5000

######################################################################
# END OF PLUGINS
######################################################################




######################################################################
# START OF GENERAL CONFIGURATIONS
######################################################################

# Turn on interactivity with mouse 
set -g mouse on

# Change the position of the status bar
set-option -g status-position bottom

# Start window numbering at specific num
set -g base-index 1          

# Renumber windows on window close
set -g renumber-windows on    

# Set escape delay for vim
set-option -sg escape-time 10

# Neovim advised this?
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -ga terminal-overrides ',xterm-256color:Tc'

#######################################################
# KEY BINDING
#######################################################

bind -n C-\\ split-window -h
bind -n C-_ split-window -v
#bind -n M- split-window -h
# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

######################################################################
# END OF GENERAL CONFIGURATIONS
######################################################################




# Initialize tpm plugin manager - DO NOT MOVE
run '~/.tmux/plugins/tpm/tpm'
